import { readFileSync, existsSync, statSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { loadTalentsCatalog } from './talents-loader.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const WORKSPACE_ROOT = join(__dirname, '..', '..');
const METADATA_PATH = join(WORKSPACE_ROOT, 'Shared', 'CommanderPower', 'commander-power-metadata.json');
const START_TALENTS_PATH = join(WORKSPACE_ROOT, 'Shared', 'CommanderPower', 'start-talents.json');
const REGISTRY_PATH = join(WORKSPACE_ROOT, 'Shared', 'Commanders', '_registry.json');
const ASSETS_CACHE_COMMANDERS = join(__dirname, '..', 'assets-cache', 'commanders');

// 解析真实头像 URL：若 assets-cache/commanders/{Runtime}.png 存在则返回带版本号的 URL
function resolveCommanderImage(runtime) {
  const fileName = `${runtime}.png`;
  const filePath = join(ASSETS_CACHE_COMMANDERS, fileName);
  if (!existsSync(filePath)) {
    return { image: '', imageReady: false, imageSource: 'missing', imageSourceLabel: '未命中' };
  }
  let version = '';
  try {
    version = `?v=${statSync(filePath).mtimeMs}`;
  } catch {
    version = '';
  }
  return {
    image: `/assets-cache/commanders/${fileName}${version}`,
    imageReady: true,
    imageSource: 'portrait-exact',
    imageSourceLabel: '真实头像',
  };
}

// Build the playable commanders set from _registry.json (single source of truth
// generated by scripts/build-commander-registry.mjs). Replaces the previous
// hardcoded PLAYABLE_COMMANDERS set.
function buildPlayableCommanderSet() {
  if (!existsSync(REGISTRY_PATH)) {
    // Fallback: if _registry.json is missing (e.g. fresh checkout before build),
    // return null so the caller can skip filtering.
    return null;
  }
  const registry = JSON.parse(readFileSync(REGISTRY_PATH, 'utf8'));
  const set = new Set();
  for (const [name, entry] of Object.entries(registry)) {
    if (entry.playable === true) {
      set.add(name);
    }
  }
  return set;
}

// integrationStatus 硬编码映射（移植自 PowerShell 脚本第 57-66 行）
const COMMANDER_INLINE_STATUS_MAP = {
  TerranRaynor: { code: 'partial-inline', tone: 'warning', note: '部分内联' },
  ZergKerrigan: { code: 'partial-inline', tone: 'warning', note: '部分内联' },
  ProtossArtanis: { code: 'partial-inline', tone: 'warning', note: '部分内联' },
  TerranNova: { code: 'external', tone: 'info', note: '外部加载' },
  ZergAbathur: { code: 'partial-inline', tone: 'warning', note: '部分内联' },
  ProtossFenix: { code: 'external', tone: 'info', note: '外部加载' },
  ProtossVorazun: { code: 'external', tone: 'info', note: '外部加载' },
  TerranSwann: { code: 'partial-inline', tone: 'warning', note: '部分内联' },
  ZergZagara: { code: 'partial-inline', tone: 'warning', note: '部分内联' },
  ProtossKarax: { code: 'external', tone: 'info', note: '外部加载' },
  TerranHorner: { code: 'external', tone: 'info', note: '外部加载' },
  ZergDehaka: { code: 'external', tone: 'info', note: '外部加载' },
  ProtossAlarak: { code: 'external', tone: 'info', note: '外部加载' },
  ZergStukov: { code: 'external', tone: 'info', note: '外部加载' },
  ProtossZeratul: { code: 'external', tone: 'info', note: '外部加载' },
  ZergStetmann: { code: 'external', tone: 'info', note: '外部加载' },
  TerranMengsk: { code: 'external', tone: 'info', note: '外部加载' },
  TerranTychus: { code: 'external', tone: 'info', note: '外部加载' },
  TerranAlenger3: { code: 'external', tone: 'info', note: '外部加载' },
};

/**
 * 加载指挥官数据
 * @returns {Array} 指挥官数组
 */
export function loadCommanders() {
  if (!existsSync(METADATA_PATH)) return [];

  const metadata = JSON.parse(readFileSync(METADATA_PATH, 'utf8'));
  let startTalentsMap = {};
  if (existsSync(START_TALENTS_PATH)) {
    const startTalents = JSON.parse(readFileSync(START_TALENTS_PATH, 'utf8'));
    startTalentsMap = startTalents.commanders || {};
  }

  const talentsCatalog = loadTalentsCatalog();

  // Build playable set from _registry.json. If the registry is missing, fall back
  // to showing all metadata entries (legacy behavior) rather than hiding everything.
  const playableSet = buildPlayableCommanderSet();

  const commanders = [];
  for (const cmdr of metadata.commanders || []) {
    const runtime = cmdr.runtime_commander;
    if (playableSet && !playableSet.has(runtime)) continue;

    const status = COMMANDER_INLINE_STATUS_MAP[runtime] || {
      code: 'unknown', tone: 'muted', note: '',
    };

    // 从 start-talents.json 读取天赋数据
    const startTalentsData = startTalentsMap[runtime];
    const startTalents = startTalentsData
      ? {
          defaultMask: 0,
          talents: (startTalentsData.talents || []).map((t) => ({
            id: t.id,
            name: t.name,
            description: t.description,
            bitMask: t.bit_mask,
            defaultEnabled: !!t.default_enabled,
            ...(t.rarity ? { rarity: t.rarity } : {}),
            ...(t.category ? { category: t.category } : {}),
          })),
        }
      : { defaultMask: 0, talents: [] };

    // 从 talents catalog 关联新天赋系统配置
    const talentsConfig = talentsCatalog.get(runtime);

    // 解析真实头像 URL
    const portrait = resolveCommanderImage(runtime);

    commanders.push({
      runtime,
      displayName: cmdr.display_name || runtime,
      bankCommander: cmdr.bank_commander || '',
      generatedCommander: cmdr.generated_commander || '',
      image: portrait.image,
      imageReady: portrait.imageReady,
      imageSource: portrait.imageSource,
      imageSourceLabel: portrait.imageSourceLabel,
      integrationStatus: status.note,
      integrationStatusCode: status.code,
      integrationTone: status.tone,
      integrationNote: status.note,
      defaultPrestigeBonusMask: 7,
      defaultPrestigePointIndex: -1,
      prestiges: (cmdr.prestiges || []).map((p) => ({
        slot: p.slot,
        bitMask: p.bit_mask,
        id: p.id,
        name: p.name || '',
        nameEn: p.name_en || '',
        tooltip: p.tooltip || '',
        tooltipEn: p.tooltip_en || '',
        extraOptions: p.extra_options || [],
      })),
      masteries: (cmdr.masteries || []).map((m) => ({
        slot: m.slot,
        category: m.category,
        id: m.id,
        name: m.name || '',
        valueFormat: m.value_format || '',
      })),
      talents: talentsConfig?.talents || [],
      startTalents,
    });
  }

  return commanders;
}
