/**
 * Generated Bootstrap 生成器
 *
 * 从 CompositionPlan.bootstrap 生成 per-commander bootstrap galaxy 文件。
 * 只包含选中 commander 的 Runtime + Adapter + Platform，排除未选中 commander 的兼容性 include。
 *
 * 目标：将 58 条注入降到 ~24 条（Raynor runtime + 23 adapters + platform）。
 *
 * 集成方式：
 * 1. launcher 在启动前调用 generateBootstrapGalaxy(plan) 生成 bootstrap galaxy 内容
 * 2. 将生成内容写入 LibE0EAE146_CompositionBootstrap.galaxy 并注入地图 Base.SC2Data
 * 3. LibE0EAE146.galaxy 移除全量 commander Runtime include，改为 include "LibE0EAE146_CompositionBootstrap"
 * 4. launcher 只注入 bootstrap.galaxyIncludes 中 purpose !== 'CompatibilityInclude' 的文件
 */

import { basename } from 'node:path';
import { writeFileSync } from 'node:fs';

/**
 * Bootstrap entry 的分类目的。
 * - CommanderRuntime: 选中 commander 的 Runtime，必须包含
 * - AdapterBootstrap: Alenger*Adapter 库，平台级必须包含
 * - PlatformKernel: 基础平台库，必须包含
 * - CompatibilityInclude: 仅因 CoreRuntime 全量 include 而需要，generated bootstrap 可排除
 */
export const BOOTSTRAP_PURPOSE = {
  COMMANDER_RUNTIME: 'CommanderRuntime',
  ADAPTER_BOOTSTRAP: 'AdapterBootstrap',
  PLATFORM_KERNEL: 'PlatformKernel',
  COMPATIBILITY_INCLUDE: 'CompatibilityInclude',
};

/**
 * 分类 manifest entry 的 bootstrap purpose。
 *
 * @param {{ owner: string, compatibilityOnly?: boolean }} entry - manifest entry
 * @param {string} selectedCommander - 选中 commander ID（如 'TerranRaynor'）
 * @returns {string} bootstrap purpose
 */
export function classifyEntry(entry, selectedCommander) {
  if (entry.owner === 'CoreRuntime.AdapterBootstrap') {
    return BOOTSTRAP_PURPOSE.ADAPTER_BOOTSTRAP;
  }
  if (entry.owner === `Commander.${selectedCommander}`) {
    return BOOTSTRAP_PURPOSE.COMMANDER_RUNTIME;
  }
  if (entry.owner === 'CoreRuntime.Platform') {
    return BOOTSTRAP_PURPOSE.PLATFORM_KERNEL;
  }
  return BOOTSTRAP_PURPOSE.COMPATIBILITY_INCLUDE;
}

/**
 * 过滤 bootstrap galaxyIncludes，只保留 generated bootstrap 需要的 entry。
 *
 * @param {Array<{ path: string, purpose: string }>} galaxyIncludes - CompositionPlan.bootstrap.galaxyIncludes
 * @param {string} [selectedCommander] - 选中 commander ID（用于从 purpose 推导）
 * @returns {{ kept: Array, excluded: Array, stats: object }}
 */
export function filterBootstrapEntries(galaxyIncludes, selectedCommander) {
  const kept = [];
  const excluded = [];

  for (const entry of galaxyIncludes) {
    const purpose = entry.purpose || BOOTSTRAP_PURPOSE.COMPATIBILITY_INCLUDE;
    if (
      purpose === BOOTSTRAP_PURPOSE.COMMANDER_RUNTIME ||
      purpose === BOOTSTRAP_PURPOSE.ADAPTER_BOOTSTRAP ||
      purpose === BOOTSTRAP_PURPOSE.PLATFORM_KERNEL
    ) {
      kept.push(entry);
    } else {
      excluded.push(entry);
    }
  }

  const stats = {
    total: galaxyIncludes.length,
    kept: kept.length,
    excluded: excluded.length,
    byPurpose: {
      [BOOTSTRAP_PURPOSE.COMMANDER_RUNTIME]: kept.filter(e => e.purpose === BOOTSTRAP_PURPOSE.COMMANDER_RUNTIME).length,
      [BOOTSTRAP_PURPOSE.ADAPTER_BOOTSTRAP]: kept.filter(e => e.purpose === BOOTSTRAP_PURPOSE.ADAPTER_BOOTSTRAP).length,
      [BOOTSTRAP_PURPOSE.PLATFORM_KERNEL]: kept.filter(e => e.purpose === BOOTSTRAP_PURPOSE.PLATFORM_KERNEL).length,
      [BOOTSTRAP_PURPOSE.COMPATIBILITY_INCLUDE]: excluded.length,
    },
  };

  return { kept, excluded, stats };
}

/**
 * 从 manifest entry 的 file 路径推导 galaxy include 名称。
 * 例如 "Base.SC2Data/LibE0EAE146_RaynorRuntime.galaxy" → "LibE0EAE146_RaynorRuntime"
 *
 * @param {string} filePath - manifest entry 的 file 字段
 * @returns {string} galaxy include 名称
 */
export function deriveIncludeName(filePath) {
  return basename(filePath).replace(/\.galaxy$/, '');
}

/**
 * 生成 bootstrap galaxy 文件内容。
 *
 * @param {object} plan - CompositionPlan
 * @param {object} [options]
 * @param {string} [options.outputLibraryName='LibE0EAE146_CompositionBootstrap'] - 生成的 galaxy 库名
 * @param {string} [options.compositionLabel] - 组合标签（用于注释）
 * @returns {{ content: string, includes: string[], stats: object }}
 */
export function generateBootstrapGalaxy(plan, options = {}) {
  const libName = options.outputLibraryName || 'LibE0EAE146_CompositionBootstrap';
  const initLibName = libName.replace(/^lib/, 'lib').replace(/^(Lib)/, 'lib') + '_InitLib';
  // Galaxy 命名约定：库名 LibXXX → 变量前缀 libXXX
  const varPrefix = libName.replace(/^L/, 'l');
  const compositionLabel = options.compositionLabel || plan.planId || 'unknown';

  const galaxyIncludes = plan.bootstrap?.galaxyIncludes || [];
  const { kept, stats } = filterBootstrapEntries(galaxyIncludes);

  const includes = kept.map(entry => deriveIncludeName(entry.path));

  // 生成 galaxy 内容
  const lines = [];
  lines.push(`// Auto-generated by sc2-composer bootstrapGenerator`);
  lines.push(`// Composition: ${compositionLabel}`);
  lines.push(`// Generated: ${new Date().toISOString()}`);
  lines.push(`//`);
  lines.push(`// This file replaces hardcoded commander Runtime includes in LibE0EAE146.galaxy.`);
  lines.push(`// Only the selected commander's Runtime + Adapter bootstrap are included.`);
  lines.push(`// Unselected commander Runtime files are NOT included.`);
  lines.push(`// Injection: ${stats.total} → ${stats.kept} entries (${stats.excluded} excluded)`);
  lines.push('');
  for (const inc of includes) {
    lines.push(`include "${inc}"`);
  }
  lines.push('');
  lines.push('//--------------------------------------------------------------------------------------------------');
  lines.push(`// Library: ${libName}`);
  lines.push('//--------------------------------------------------------------------------------------------------');
  lines.push(`bool ${varPrefix}_InitLib_completed = false;`);
  lines.push('');
  lines.push(`void ${initLibName} () {`);
  lines.push(`    if (${varPrefix}_InitLib_completed) {`);
  lines.push(`        return;`);
  lines.push(`    }`);
  lines.push(`    ${varPrefix}_InitLib_completed = true;`);
  lines.push('');

  // initSequence — 如果 plan.bootstrap.initSequence 有条目，生成调用
  const initSequence = plan.bootstrap?.initSequence || [];
  if (initSequence.length > 0) {
    lines.push('    // Init sequence from CompositionPlan');
    for (const step of initSequence) {
      if (step.function) {
        lines.push(`    // phase: ${step.phase || 'unknown'}`);
        lines.push(`    ${step.function}();`);
      }
    }
  } else {
    lines.push('    // No init sequence — adapter InitLib is handled by AdapterBootstrap');
  }

  lines.push('}');
  lines.push('');

  return {
    content: lines.join('\n'),
    includes,
    stats,
  };
}

/**
 * 将生成的 bootstrap galaxy 写入文件。
 *
 * @param {object} plan - CompositionPlan
 * @param {string} outputPath - 输出文件路径
 * @param {object} [options] - 同 generateBootstrapGalaxy
 * @returns {{ content: string, includes: string[], stats: object, outputPath: string }}
 */
export function generateBootstrapFile(plan, outputPath, options = {}) {
  const result = generateBootstrapGalaxy(plan, options);
  writeFileSync(outputPath, result.content, 'utf-8');
  return { ...result, outputPath };
}
